version: '3'
services:
  copypasta:
    image: copypasta:latest
    container_name: copypasta
    ports:
      - "8443:8080"
    environment:
      - TZ=America/New_York
    volumes:
      - ./:/srv
    restart: unless-stopped